# Generated by Django 5.1.4 on 2025-01-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_choice_voter_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='choice_id',
            new_name='choice',
        ),
    ]
