# Generated by Django 5.1.4 on 2025-01-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_answers_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
