# Generated by Django 5.1.4 on 2025-02-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_not_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(verbose_name='Born date')),
                ('grado', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=10)),
            ],
        ),
    ]
